apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-service
  namespace: easystay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: property-service
  template:
    metadata:
      labels:
        app: property-service
    spec:
      containers:
      - name: property-service
        image: easystay/property-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: property-service
  namespace: easystay
spec:
  type: ClusterIP
  selector:
    app: property-service
  ports:
  - port: 8082
    targetPort: 8082
